language: python
python:
  - "2.7.10"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - "pip install -r requirements.txt"
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - python -m unittest discover
  #- coverage run --omit="*virtualenv*","limber*" manage.py test
branches:
  only:
  - develop
  - master
  - feature/test
env:
  global:
    - TRAVIS_BUILD=true
after_success:
    - coveralls